# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "vineet" ]
  pull_request:
    branches: [ "vineet" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js [18.16.1]
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.1
        cache: 'npm'
    - run: npm ci
    - run: wdio run ./wdio.conf.js

